# sonar-project.properties
sonar.projectKey=Habited_python-project-52
sonar.organization=habited

sonar.sources=task_manager
sonar.tests=task_manager
sonar.test.inclusions=**/tests/**

# Покрытие
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# Исключения
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/static/**,**/media/**
sonar.coverage.exclusions=**/admin.py,**/apps.py,**/migrations/**