# Generated by Django 6.0.1 on 2026-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Users',
        ),
    ]
