# Generated by Django 6.0.1 on 2026-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_rename_women_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='password_validation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
