# Generated by Django 6.0.1 on 2026-02-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_users_last_name_users_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
    ]
