# Generated by Django 6.0.1 on 2026-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_rename_name_users_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startus_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(blank=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_validation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подтвердить пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.TextField(blank=True, verbose_name='Имя пользователя'),
        ),
    ]
