# Generated by Django 6.0.1 on 2026-03-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_status_alter_users_options_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='startus_name',
            new_name='status_name',
        ),
    ]
