# Generated by Django 6.0.1 on 2026-03-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_rename_startus_name_status_status_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statuses',
        ),
    ]
