# Generated by Django 6.0.1 on 2026-03-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_rename_status_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
