# Generated by Django 6.0.1 on 2026-03-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_delete_statuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
