# Generated by Django 4.2.29 on 2026-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_statuses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='status_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
