# Generated by Django 4.2.29 on 2026-03-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_id'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
