# Generated by Django 4.2.29 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
