# Generated by Django 6.0.1 on 2026-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='Описание отсутствует', max_length=5000, verbose_name='Оипсание'),
        ),
    ]
