# Generated by Django 4.2.29 on 2026-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
        ('tasks', '0005_alter_tasks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='labels.label'),
        ),
    ]
