# Generated by Django 4.2.29 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-time_create'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='Описание отсутствует', max_length=5000, verbose_name='Описание'),
        ),
    ]
