# Generated by Django 4.2.29 on 2026-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_options_alter_tasks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
